# SPDX-FileCopyrightText: 2026 BASE COMPUTING S.A.S.
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(actions)"
