version = 1

SPDX-PackageName = "basis-network-org"
SPDX-PackageSupplier = "Basis Network <contact@basisnetwork.com.co>"
SPDX-PackageDownloadLocation = "https://github.com/basis-network/.github"

[[annotations]]
path = ["LICENSE", "NOTICE", "CODE_OF_CONDUCT.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Basis Network"
SPDX-License-Identifier = "Apache-2.0"
