# SPDX-FileCopyrightText: 2026 Basis Network
# SPDX-License-Identifier: Apache-2.0
#
# This repository is documents. The one thing worth checking mechanically is
# that every one of them states its copyright and licence.
name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  reuse:
    name: REUSE compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5
